name: .NET

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Build
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="WindowWalker-$tag"
          dotnet publish 'Microsoft.Plugin.WindowWalker.csproj' --framework netcoreapp3.1  -c Release -o "$release_name"
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "WindowWalker*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
