name: Publish Release

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'Microsoft.Plugin.WindowWalker.csproj' --framework netcoreapp3.1  -c Release -o "WindowWalker"
          7z a -tzip "WindowWalker.zip" "./WindowWalker/*"
          rm -r "WindowWalker"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "WindowWalker*"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
